### ISSUE TITLE
Fix abrupt repaint

### ISSUE THREAD

**Issue by abdonrd** [polymer-day/web#105]
Check the GIF:

![polymerday](https://cloud.githubusercontent.com/assets/1007051/19016099/3d092d4c-8811-11e6-8b91-bbb592b3b108.gif)

**Comment by abdonrd** [comment]
Closed by #106.

**Comment by abdonrd** [comment]
@kcmr oops! The problem persist if you enter to [https://www.polymerday.com](https://www.polymerday.com). :(
`/` redirects to `/home`

In `/home` works well. But not in `/`.

The same problem if you change to another route. Example: from `/schedule` to `/venue`.

**Comment by kcmr** [comment]
Still happens on mobile :/
Please, reopen...
