### ISSUE TITLE
Add Open Graph meta tags

### ISSUE THREAD

**Issue by abdonrd** [polymer-day/web#107]
Example: [GDGSpain/gdg.es/index.html#L45-L61](https://github.com/GDGSpain/gdg.es/blob/develop/index.html#L45-L61)

Card validator: https://cards-dev.twitter.com/validator
Facebook Sharing Debugger: https://developers.facebook.com/tools/debug/

**Comment by abdonrd** [comment]
I propose use the [summary-large-image](https://dev.twitter.com/cards/types/summary-large-image) in Twitter.
I think the image, at least, must contain the logo, the date and the city. Something like:

<img width="660" alt="screen shot 2016-10-03 at 19 01 34" src="https://cloud.githubusercontent.com/assets/1007051/19046537/22fc4216-899e-11e6-8420-153f4d767632.png">

**Comment by jorgecasar** [comment]
Thanks. I included ;)
