### ISSUE TITLE
Translation is sometimes not working in English

### ISSUE THREAD

**Issue by TimvdLippe** [polymer-day/web#108]
![image](https://cloud.githubusercontent.com/assets/5948271/19055982/05c36fa2-89c7-11e6-9721-6b55a55bef75.png)
Both the tab content as well as the extra buttons are empty/undefined.

**Comment by jorgecasar** [comment]
I don't know why sometime doesn't load well. If you refresh the page should work. I will take a deep look. Thanks,

**Comment by TimvdLippe** [comment]
Sadly this issue does not resolve either when refreshing the page.
