### ISSUE TITLE
No navigation available on the homepage

### ISSUE THREAD

**Issue by TimvdLippe** [polymer-day/web#109]
Opening the homepage does not show any navigation:
![image](https://cloud.githubusercontent.com/assets/5948271/19056004/218ff89a-89c7-11e6-9e24-304e4d23dcfa.png)

It seems that the actual navigation links are positioned offscreen to the left.

**Comment by jorgecasar** [comment]
I don't know why sometime spent so much time to load data from Firebase. If you refresh the page should work. I will take a deep look. Thanks,

**Comment by TimvdLippe** [comment]
Sadly refreshing the page does not resolve the issue.

**Comment by kcmr** [comment]
I think this issue is a duplicate of https://github.com/polymer-day/web/issues/108 that is closed.

**Comment by TimvdLippe** [comment]
Yes confirmed fixed. Thanks!
