### ISSUE TITLE
Translate Registro to Register in english

### ISSUE THREAD

**Issue by abdonrd** [polymer-day/web#111]
<img width="764" alt="screen shot 2016-10-04 at 08 47 57" src="https://cloud.githubusercontent.com/assets/1007051/19064713/525187bc-8a0f-11e6-95a4-a58046ddee9d.png">

**Comment by jorgecasar** [comment]
Schedule will be in one language, the la guaje of the talk.

**Comment by jorgecasar** [comment]
Finally I put both.
