### ISSUE TITLE
Fix the redirects

### ISSUE THREAD

**Issue by abdonrd** [polymer-day/web#112]
<img width="998" alt="screen shot 2016-10-04 at 08 44 10" src="https://cloud.githubusercontent.com/assets/1007051/19064732/6966195e-8a0f-11e6-9009-d14fe7a65171.png">

**Comment by reiaguilera** [comment]
I'll check Thx

**Comment by reiaguilera** [comment]
resolved 🏁

**Comment by reiaguilera** [comment]
Close Issus Plz @jorgecasar

**Comment by abdonrd** [comment]
Closed!
