### ISSUE TITLE
Missing class sr-only in the speakers section for Firefox

### ISSUE THREAD

**Issue by felixzapata** [polymer-day/web#116]
The class `sr-only` is missing

**Comment by kcmr** [comment]
The class has been moved to polymerday-classes because it's used along the app. If the class is not applied, we need to import that component and add the style module id to the style include attribute.

**Comment by felixzapata** [comment]
@kcmr ok. The problem only affects to Firefox.

**Comment by jorgecasar** [comment]
@kcmr the component import the style `polymerday-classes`. In Chrome works fine

**Comment by felixzapata** [comment]
@jorgecasar maybe is a problem related with some selector and the Shadow DOM like other similar issues fixed before.
