### ISSUE TITLE
Recover app's text color

### ISSUE THREAD

**Issue by isorna** [polymer-day/web#12]
It was #
![captura de pantalla 2016-09-02 a las 10 35 09](https://cloud.githubusercontent.com/assets/39324/18197764/3fb03d4e-70f9-11e6-90f5-d2b873b75c22.png)
![captura de pantalla 2016-09-02 a las 10 35 16](https://cloud.githubusercontent.com/assets/39324/18197763/3faf2d46-70f9-11e6-8c65-07f22dc83a5b.png)

4788C8, from the header.

**Comment by kcmr** [comment]
@isorna are you referring to the date?

**Comment by isorna** [comment]
To the content's text color:
Madrid
We're coming soon...
Stay Tuned
...

¬--------------------
Alvaro Isorna

2016-09-04 1:38 GMT+02:00 Kus Cámara notifications@github.com:
