### ISSUE TITLE
Create firebase database with two collections for speakers and talks

### ISSUE THREAD

**Issue by ccanado** [polymer-day/web#17]
With the intention to ease changes in speakers and talks variations. Store speakers and talks entities information in a simple firebase database where the data will be collected to show in view components
Create two non sql collections.

**Comment by SamuelDorado** [comment]
I'll take this one :)

**Comment by SamuelDorado** [comment]
Should we create another collection for sponsors?

**Comment by jorgecasar** [comment]
Yes, this is already created and discussed in #29

**Comment by SamuelDorado** [comment]
Have a look...
[polymerdayFirebase .json.txt](https://github.com/polymer-day/web/files/472052/polymerdayFirebase.json.txt)

**Comment by SamuelDorado** [comment]
This is even better
[polymerdayFirebaseRelationships .json.txt](https://github.com/polymer-day/web/files/472118/polymerdayFirebaseRelationships.json.txt)

**Comment by jorgecasar** [comment]
Schedule should be the id of the talk, to avoid duplicate info and have to change the timetwice.

Firebase manage the array as object with random key, but using polymerfire element that's doesn't care.

**Comment by SamuelDorado** [comment]
Have a look to this one!
[polymerdayFirebase .json.txt](https://github.com/polymer-day/web/files/474741/polymerdayFirebase.json.txt)
