### ISSUE TITLE
Menu refactoring

### ISSUE THREAD

**Issue by ccanado** [polymer-day/web#19]
Make changes needed to follow the established design

![header-menu](https://cloud.githubusercontent.com/assets/2075986/18448582/018e76a8-792c-11e6-8732-79e2975bc29a.png)

**Comment by isaacsc** [comment]
I'll take this.

**Comment by jorgecasar** [comment]
There are a bug in Firefox that was solved in the previous version by @felixzapata with #14

**Comment by jorgecasar** [comment]
Created issue #32
Closed by PR #33
