### ISSUE TITLE
Speaker Component

### ISSUE THREAD

**Issue by ccanado** [polymer-day/web#23]
Web component view of speaker information unit.

_(data from host element throw a property or attribute of the element)_
`<polymerday-speaker speaker="{{speakerJson}}"></polymerday-speaker>`

![speaker-detail](https://cloud.githubusercontent.com/assets/2075986/18449434/6f52c9d4-792f-11e6-87ae-83265777f00b.png)

**Comment by sjuanman** [comment]
I'll take this

**Comment by jorgecasar** [comment]
Pull request this one with #25 together

**Comment by jorgecasar** [comment]
@sjuanman How is it going? We are adding talks and we need this component.
