### ISSUE TITLE
Talk Component

### ISSUE THREAD

**Issue by ccanado** [polymer-day/web#24]
Web component view of talk information unit. With expand/collapse functionality.

_(data from host element throw a property or attribute of the element)_
`<polymerday-talk talk="{{talkJson}}"></polymerday-talk>`

![talk-detail](https://cloud.githubusercontent.com/assets/2075986/18449608/0d67135a-7930-11e6-8228-1d7d9d2f4c61.png)

**Comment by jlsanchezsanz** [comment]
I'll take this.

**Comment by jorgecasar** [comment]
@jlsanchezsanz this was made by @kcmr

**Comment by jlsanchezsanz** [comment]
Your comment is 6 days late :P, this issue was assigned to me in the beginning but later @kcmr requested it.

**Comment by jorgecasar** [comment]
@ccanado assign only to 1 person, @kcmr made it and @jlsanchezsanz was working on too

**Comment by ccanado** [comment]
This issue was assigned to @jlsanchezsanz  at the begining but, after conversation in slack, @kcmr and @jlsanchezsanz exchanged sponsors and talk components assignments and this issue was changed assignement only for @kcmr. It is suppose that @jlsanchezsanz should not be working on it.
At least that was the intention. Maybe I made the change wrong. My apologies

**Comment by jorgecasar** [comment]
OK, this comment from github wasn't clear enough, sorry "@ccanado assigned @jlsanchezsanz and @kcmr and unassigned @kcmr and @jlsanchezsanz"
