### ISSUE TITLE
Speakers laying out

### ISSUE THREAD

**Issue by ccanado** [polymer-day/web#25]
Create layout for Speakers section.
Obtain speakers data from firebase and iterate with `polymerday-speaker` component
**Dependencies with issues #17 and #23**

**Design**:
![speakers deskstop](https://cloud.githubusercontent.com/assets/2075986/18449849/10ac3d8c-7931-11e6-8245-0b87b05c0f21.png)

**Comment by jorgecasar** [comment]
@sjuanman set a id per speaker to allow anchor links

**Comment by jorgecasar** [comment]
Deployed.

We have to fix some icon position and icon design (svg).
Mobile version
