### ISSUE TITLE
Schedule laying out

### ISSUE THREAD

**Issue by ccanado** [polymer-day/web#26]
Create layout for Schedule section.
Obtain talks data from firebase and iterate with `polymerday-talk` component
**Dependencies with issues #17 and #24**

**Design Desktop**:
![schedule deskstop](https://cloud.githubusercontent.com/assets/2075986/18449924/601d67b0-7931-11e6-8778-278ac2535c67.png)

**Design Mobile**:
![schedule mobile](https://cloud.githubusercontent.com/assets/948953/18642314/7bec93ac-7ea0-11e6-84b1-ab3104ada759.png)

**Comment by jorgecasar** [comment]
Close with #24
