### ISSUE TITLE
Fix paper-tabs width on mobile

### ISSUE THREAD

**Issue by isorna** [polymer-day/web#4]
Modify the css so that the full content of each tab is visible on mobile. The file to be modified is polymerday-app/polymerday-app.html
![captura de pantalla 2016-08-31 a las 9 32 14](https://cloud.githubusercontent.com/assets/39324/18120099/3c20e148-6f5e-11e6-9fed-ab474f92ce24.png)

**Comment by jorgecasar** [comment]
Fixed with refactor
