### ISSUE TITLE
Fix sponsors layout on mobile

### ISSUE THREAD

**Issue by isorna** [polymer-day/web#5]
Set up css so that only a single column of sponsors' cards is shown, centering them accordingly.

The file to modify is view-sponsors.html

![captura de pantalla 2016-08-31 a las 11 05 01](https://cloud.githubusercontent.com/assets/39324/18123006/3fe05d1e-6f6c-11e6-8dfe-2d9f6f326c1f.png)

**Comment by jorgecasar** [comment]
I guess, it's fixed with refactor
