### ISSUE TITLE
Schedule: colour contrasts

### ISSUE THREAD

**Issue by felixzapata** [polymer-day/web#52]
It is necessary modify the contrast:
- the disabled button
- between the blue background and the title of the talk

**Comment by SamuelDorado** [comment]
I'll take this one

**Comment by felixzapata** [comment]
@SamuelDorado I prefer to take this one because I can talk with the designer directly and set the new colours.

**Comment by jorgecasar** [comment]
@SamuelDorado the steps to contribute are as we describe in README:
- Create issue
- Create brach with the issue id
- PR from this brach to master

@felixzapata created it following the steps, then he will do it.
