### ISSUE TITLE
Create component for speaker's gallery

### ISSUE THREAD

**Issue by isorna** [polymer-day/web#6]
This is the snippet we need.

![speakers-transition](https://cloud.githubusercontent.com/assets/39324/18123297/8f2dea2a-6f6d-11e6-8aac-16adf187bc44.gif)

**Comment by ccanado** [comment]
@isorna, with the new design, this proposal is obsolete. Do you think we can close it for now?

**Comment by itscesarvillar** [comment]
I like this one very much. Not whole flow but the part where image is placed on the left and text is next to... maybe we can use for a talk detail...

**Comment by jorgecasar** [comment]
Related with #25

**Comment by jorgecasar** [comment]
Duplicated by #23
