### ISSUE TITLE
Fix long event name in schedule

### ISSUE THREAD

**Issue by jorgecasar** [polymer-day/web#61]
Events with long name or small screens jump to a new line.

**Comment by kcmr** [comment]
Could you please add a screenshot? I think this is the desired behavior.

![captura de pantalla 2016-09-25 a las 15 49 06](https://cloud.githubusercontent.com/assets/92611/18815674/a964271e-8337-11e6-94f9-0714bddc30d4.png)

**Comment by kcmr** [comment]
I've just added 3 commits more to PR #79 
One of them fix this issue.
