### ISSUE TITLE
Add language of the talk in schedule

### ISSUE THREAD

**Issue by jorgecasar** [polymer-day/web#62]
There are talks in Spanish and English. It would be good to mark the speaker language somehow

**Comment by jorgecasar** [comment]
Each talk in the language of the speaker

**Comment by abdonrd** [comment]
A simple approach: 

<table>
  <tr>
    <td><img src="https://cloud.githubusercontent.com/assets/1007051/19110823/88c04a52-8afc-11e6-82d5-b1df73d76d9a.png"></td>
    <td><img src="https://cloud.githubusercontent.com/assets/1007051/19110827/8b929596-8afc-11e6-8c46-deab1462d4ed.png"></td>
  </tr>
</table>

**Comment by abdonrd** [comment]
https://github.com/polymer-day/web/pull/119
