### ISSUE TITLE
Missing menu in Firefox (production)

### ISSUE THREAD

**Issue by felixzapata** [polymer-day/web#83]
The menu is missing in Firefox under production website and it is strange because the same issue happens under Chrome if you open from your local development.

![polymer_day_-_2016-09-27_08 59 25](https://cloud.githubusercontent.com/assets/997038/18863305/ec91127c-8490-11e6-8a5a-5487a5befb74.png)

**Comment by felixzapata** [comment]
I think the problem is related with the locales file (or the polyfill for the localization component).

![polymer_day_-_2016-09-27_08 59 25](https://cloud.githubusercontent.com/assets/997038/18864071/d4125644-8494-11e6-89fa-8ebaddd78c43.png)

Over the layer for the cookies message, the text says "Undefined".

**Comment by felixzapata** [comment]
In Firefox, the response from the locales file is null:

![polymer_day_-_2016-09-27_08 59 25](https://cloud.githubusercontent.com/assets/997038/18864257/c3b9fc38-8495-11e6-861d-ebe90f63ea2a.png)

**Comment by jorgecasar** [comment]
I guess this is solved. The problem was the language that Firefox return "en-US" and Chrome "en". Now we take the first 2 letters.

**Comment by felixzapata** [comment]
It works now. Thanks
