### ISSUE TITLE
Upgrade hotels with design

### ISSUE THREAD

**Issue by ccanado** [polymer-day/web#89]
Attached to this issue you can find the design to apply.
Notes:
- Hotel Cards are the links to the hotel
- All contents are the in Sketch, including images of hotels

![polymerday-accomodation-1](https://cloud.githubusercontent.com/assets/2075986/18869786/2735b050-84ae-11e6-8db9-2169b296c4a2.png)

![polymerday-accomodation-2](https://cloud.githubusercontent.com/assets/2075986/18869792/2c06275e-84ae-11e6-8296-1a854fb2d723.png)

**Comment by kcmr** [comment]
I can take this one if nobody is working on it yet.

**Comment by jorgecasar** [comment]
Thanks!
