### ISSUE TITLE
Laying Out Microsite Sponsors

### ISSUE THREAD

**Issue by ccanado** [polymer-day/web#97]
Laying out the first microsite. Then, take this as base for the others sponsors microsites (Platinium and Gold have that extra).
We can start with Kairos microsites until close negotiations with other sponsors.

![polymerday-sponsors-microsite-1](https://cloud.githubusercontent.com/assets/2075986/18917685/c7d63328-8598-11e6-9f6e-eb58f74d6139.png)

![polymerday-sponsors-microsite-2](https://cloud.githubusercontent.com/assets/2075986/18917687/c8c5233e-8598-11e6-8ae5-137e29a5cab0.png)

**Comment by jorgecasar** [comment]
The sponsor page will have a header image and array of services (image and text) with this structure in Firebase:

```
{
  banner: {
    image: {
      big: "",
      small: ""
    }
    link: ""
  },
  services: [{
     image: "",
     text: "",
     link: ""
  }]
}
```

**Comment by ccanado** [comment]
Added here mobile design

![polymerday-sponsors-mobile](https://cloud.githubusercontent.com/assets/2075986/18943735/c869da86-8621-11e6-8c96-0a4e06a063ad.png)

**Comment by jorgecasar** [comment]
This issues is ver important for sponsor. Last week we close all sponsors and we need this page for 3 of them.

**Comment by jlsanchezsanz** [comment]
I can take this.

**Comment by jorgecasar** [comment]
Ok, for the boxes use the component implemented in venue for hotels.

**Comment by jlsanchezsanz** [comment]
Sure, thanks!

**Comment by jorgecasar** [comment]
I updated the data source
