### ISSUE TITLE
Fix app-indexeddb-mirror error with polymer-build

### ISSUE THREAD

**Issue by abdonrd** [polymer-day/web#99]
If open [polymerday.com](https://www.polymerday.com) with Safari breaks:

![screen shot 2016-10-01 at 18 04 51](https://cloud.githubusercontent.com/assets/1007051/19015286/a6af903e-8801-11e6-9d5f-6695421bfc73.png)

If open [polymerday.com](https://www.polymerday.com) with Chrome only `connecting..` and no `connected!`:

![screen shot 2016-10-01 at 18 07 49](https://cloud.githubusercontent.com/assets/1007051/19015304/069ba7d0-8802-11e6-9e81-c20cc0181e2d.png)

Reference issue: https://github.com/Polymer/polymer-build/issues/22

**Comment by jorgecasar** [comment]
I deleted the feauture while the issue persists

**Comment by abdonrd** [comment]
Closing and old issue.
